id: IB8A6B5C7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:50:28+00:00'
last_modified: '2022-06-15T16:24:54.659877+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD194
  title: ཟངས་རི་རྫོང་གི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E9EE:
      image_group_id: I4PD4607
      title: Volume 1 of zangs ri rdzong gi dkar chag
      total_pages: 916
      order: 1
      base_file: E9EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
